SCENARIO_CONFIGS = {
    "NORMAL_MISSION": {
        "observation_interval_s": 60.0,
        "smoke_score_weights": [0.1, 0.3, 0.4, 0.2],
        "priority_threshold": 0.6,
        "mode": "CRUISE",
        "battery_drain_rate": 0.02,
        "solar_efficiency": 1.0,
        "thermal_base": 20.0,
        "comm_status": "NOMINAL",
        "description": "Standard mission operations with balanced observation schedule.",
    },
    "WILDFIRE_DETECTION": {
        "observation_interval_s": 30.0,
        "smoke_score_weights": [0.05, 0.1, 0.3, 0.55],
        "priority_threshold": 0.5,
        "mode": "OBSERVE",
        "battery_drain_rate": 0.025,
        "solar_efficiency": 1.0,
        "thermal_base": 22.0,
        "comm_status": "NOMINAL",
        "description": "Frequent observations prioritizing high-confidence smoke detections.",
    },
    "HIGH_PRIORITY": {
        "observation_interval_s": 20.0,
        "smoke_score_weights": [0.0, 0.05, 0.15, 0.8],
        "priority_threshold": 0.4,
        "mode": "OBSERVE",
        "battery_drain_rate": 0.03,
        "solar_efficiency": 1.0,
        "thermal_base": 24.0,
        "comm_status": "NOMINAL",
        "description": "Critical priority observation imminent with rapid downlink.",
    },
    "LOW_BATTERY": {
        "observation_interval_s": 120.0,
        "smoke_score_weights": [0.2, 0.4, 0.3, 0.1],
        "priority_threshold": 0.7,
        "mode": "SAFE",
        "battery_drain_rate": 0.06,
        "solar_efficiency": 0.6,
        "thermal_base": 18.0,
        "comm_status": "NOMINAL",
        "description": "Battery draining rapidly. Load shedding active.",
    },
    "THERMAL_WARNING": {
        "observation_interval_s": 60.0,
        "smoke_score_weights": [0.1, 0.3, 0.4, 0.2],
        "priority_threshold": 0.6,
        "mode": "CRUISE",
        "battery_drain_rate": 0.02,
        "solar_efficiency": 1.0,
        "thermal_base": 45.0,
        "comm_status": "NOMINAL",
        "description": "Elevated thermal readings. Thermal control system compensating.",
    },
    "COMM_LOSS": {
        "observation_interval_s": 60.0,
        "smoke_score_weights": [0.1, 0.3, 0.4, 0.2],
        "priority_threshold": 0.6,
        "mode": "SAFE",
        "battery_drain_rate": 0.02,
        "solar_efficiency": 1.0,
        "thermal_base": 20.0,
        "comm_status": "LOSS_OF_SIGNAL",
        "description": "Communications failure. Stored data awaiting downlink.",
    },
    "RECOVERY": {
        "observation_interval_s": 90.0,
        "smoke_score_weights": [0.15, 0.35, 0.35, 0.15],
        "priority_threshold": 0.6,
        "mode": "CRUISE",
        "battery_drain_rate": 0.02,
        "solar_efficiency": 0.9,
        "thermal_base": 21.0,
        "comm_status": "DEGRADED",
        "description": "Recovering from fault. Systems returning to nominal.",
    },
}

GROUND_STATIONS = [
    {
        "id": "BOULDER",
        "name": "Boulder, CO",
        "lat": 40.0150,
        "lon": -105.2705,
        "alt_m": 1655,
        "band": "S",
        "data_rate_mbps": 2.0,
    },
    {
        "id": "FAIRBANKS",
        "name": "Fairbanks, AK",
        "lat": 64.8378,
        "lon": -147.7164,
        "alt_m": 136,
        "band": "X",
        "data_rate_mbps": 10.0,
    },
    {
        "id": "SVALBARD",
        "name": "Svalbard, Norway",
        "lat": 78.2306,
        "lon": 15.3894,
        "alt_m": 474,
        "band": "X",
        "data_rate_mbps": 15.0,
    },
    {
        "id": "SINGAPORE",
        "name": "Singapore",
        "lat": 1.3521,
        "lon": 103.8198,
        "alt_m": 15,
        "band": "Ka",
        "data_rate_mbps": 25.0,
    },
    {
        "id": "PUNTA_ARENAS",
        "name": "Punta Arenas, Chile",
        "lat": -53.1638,
        "lon": -70.9171,
        "alt_m": 27,
        "band": "S",
        "data_rate_mbps": 3.0,
    },
]

ORBIT_PARAMS = {
    "altitude_km": 500.0,
    "inclination_deg": 97.4,
    "eccentricity": 0.0,
    "period_minutes": 94.7,
    "right_ascension_deg": 0.0,
}

THERMAL_NODES = [
    "BATTERY",
    "SOLAR_PANEL",
    "PROCESSOR",
    "ANTENNA",
    "STRUCTURE",
]

EVENT_TYPES = [
    "OBSERVATION_CAPTURED",
    "AI_ANALYSIS_COMPLETE",
    "PRIORITY_ASSIGNMENT",
    "DOWNLINK_QUEUED",
    "GROUND_CONTACT",
    "DOWNLINK_STARTED",
    "DOWNLINK_COMPLETE",
]
